local outline = CreateFrame("Frame", nil, UIParent)
local top = outline:CreateLine()
top:SetColorTexture(1, 1, 1, 1)
top:SetStartPoint("TOPLEFT")
top:SetEndPoint("TOPRIGHT")
top:SetThickness(2)
local bottom = outline:CreateLine()
bottom:SetColorTexture(1, 1, 1, 1)
bottom:SetStartPoint("BOTTOMLEFT")
bottom:SetEndPoint("BOTTOMRIGHT")
bottom:SetThickness(2)
local left = outline:CreateLine()
left:SetColorTexture(1, 1, 1, 1)
left:SetStartPoint("TOPLEFT")
left:SetEndPoint("BOTTOMLEFT")
left:SetThickness(2)
local right = outline:CreateLine()
right:SetColorTexture(1, 1, 1, 1)
right:SetStartPoint("TOPRIGHT")
right:SetEndPoint("BOTTOMRIGHT")
right:SetThickness(2)

function Vimp_Outline(frame)
    if not frame then
        outline:Hide()
        return
    end
    outline:SetAllPoints(frame)
 outline:Show()
 outline:SetFrameStrata("TOOLTIP")
end